import { AxiosResponse } from "axios";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Tabs from "../components/Tabs";
import { fetchCategories } from "../http";
import { ICategory, ICollectionResponse } from "../types";
interface IPropTypes {
  categories: {
    items: ICategory[];
  };
}

const Home: NextPage<IPropTypes> = ({ categories }) => {
  return (
    <div>
      <Head>
        <title>CS ROADMAP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Tabs categories={categories.items} />
      <main>
        <h1 className="text-primary-dark ">Welcome to CS ROADMAP</h1>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  // fetch categories
  // We're going to use Axios
  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await fetchCategories();

  return {
    props: {
      categories: {
        items: categories.data,
      },
    },
  };
};

export default Home;
